(deftheme patrick-local
  "Created 2013-07-12.")

(custom-theme-set-faces
 'patrick-local
 '(cursor ((t (:background "dark goldenrod"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:box (:line-width 1 :color "blue" :style released-button) :foreground "#a40000" :background "gold"))))
 '(minibuffer-prompt ((t (:foreground "#ffffff" :weight bold))))
 '(highlight ((t (:background "DodgerBlue4"))))
 '(region ((t (:background "blue" :foreground "white"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "black" :background "#8cc4ff"))))
 '(trailing-whitespace ((t (:background "#ef2929"))))
 '(font-lock-builtin-face ((t (:foreground "MediumOrchid1"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "DarkOrange1"))))
 '(font-lock-constant-face ((t (:foreground "turquoise3" :weight bold))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#a49090"))))
 '(font-lock-keyword-face ((t (:foreground "SeaGreen1"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "gold"))))
 '(font-lock-type-face ((t (:foreground "turquoise3"))))
 '(font-lock-variable-name-face ((t (:foreground "#b35020"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "orange red" :inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "DodgerBlue2" :underline t))))
 '(link-visited ((t (:inherit link :foreground "SlateBlue4" :underline t))))
 '(header-line ((t (:inherit mode-line :background "grey20" :foreground "grey90" :box nil))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "LightSkyBlue1" :background "DeepSkyBlue4"))))
 '(mode-line-buffer-id ((t (:underline "red" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground "#2e3436" :background "#888a85" :inherit (mode-line)))))
 '(isearch ((t (:background "#ce5c00" :foreground "#ffffff"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "DarkOrange4"))))
 '(match ((t (:background "SkyBlue"))))
 '(next-error ((t (:background "SkyBlue" :inherit (region)))))
 '(query-replace ((t (:foreground "black" :background "white" :inherit (isearch)))))
 '(powerline-active1 ((t (:inherit mode-line :background "orange2" :foreground "black"))))
 '(powerline-active2 ((t (:inherit mode-line :background "goldenrod4" :foreground "black"))))
 '(powerline-inactive1 ((t (:inherit mode-line :foreground "chartreuse"))))
 '(default ((t (:inherit nil :background "#102010" :foreground "LightCyan1" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120)))))

(provide-theme 'patrick-local)
